#!/bin/bash
# -*- coding: utf-8 -*-
# cluster configure file

include /etc/redis/redis.conf

port 6379
# slaveof spring.season.com 6379
requirepass season_4U
# masterauth season_4U

dir /var/redis/data/cluster
dbfilename cluster.rdb
appendfilename cluster.aof
cluster-config-file cluster.conf

pidfile /var/redis/run/cluster.pid
logfile /var/log/redis/cluster.log

cluster-node-timeout 300000
cluster-require-full-coverage yes
cluster-allow-reads-when-down yes
cluster-replica-no-failover no
cluster-slave-validity-factor 10
cluster-allow-replica-migration yes
cluster-migration-barrier 1

