#!/bin/bash
# -*- coding: utf-8 -*-
# sentinel configure file

include /etc/redis/redis.conf

port 26379
dir /var/redis/data/sentinel

pidfile /var/redis/run/sentinel.pid
logfile /var/log/redis/sentinel.log

sentinel monitor season xxx.xxx.xxx.xxx 6379 2
sentinel auth-pass season season_4U
sentinel down-after-milliseconds season 300000
sentinel failover-timeout season 300000
sentinel parallel-syncs season 1

