#!/bin/bash
# -*- coding: utf-8 -*-
# standalone configure file

include /etc/redis/redis.conf

port 6379
# tls-port 6379
# slaveof redis.season.com 6379
requirepass season_4U
# masterauth season_4U

dir /var/redis/data/standalone
dbfilename standalone.rdb
appendfilename standalone.aof
cluster-config-file nodes.conf

pidfile /var/redis/run/standalone.pid
logfile /var/log/redis/standalone.log

# tls-auth-clients no
# tls-replication yes

