#!/bin/bash
# -*- coding: utf-8 -*-
# standalone configure file

include /etc/redis/redis.conf

port 6379
# slaveof spring.season.com 6379
requirepass season_4U
# masterauth season_4U

dir /var/redis/data/standalone
dbfilename standalone.rdb
appendfilename standalone.aof

pidfile /var/redis/run/standalone.pid
logfile /var/log/redis/standalone.log

