Server {
    org.apache.zookeeper.server.auth.DigestLoginModule required
    user_admin="admin_4U"
    user_kafka="kafka_4U"
    user_hbase="hbase_4U";
};

Client {
    org.apache.zookeeper.server.auth.DigestLoginModule required
    username="admin"
    password="admin_4U";
};