#######################################################################################################################
#                                _      _      _                                   _                                  #
#                               | | o  | |    | |                                 | |                                 #
#                               | |    | |  _ | |   _   __, _|_         _  _  _   | |                                 #
#                               |/  |  |/  |/ |/ \_|/  /  |  |   |   | / |/ |/ |  |/                                  #
#                               |__/|_/|__/|__/\_/ |__/\_/|_/|_/o \_/|/  |  |  |_/|__/                                #
#                               |\                                  /|                                                #
#                               |/                                  \|                                                #
#######################################################################################################################
#
# 文件位置: /etc/filebeat/filebeat.yml
#


# =====================================================================================================================
# 日志采集部分
# =====================================================================================================================
filebeat.inputs:
- type: log
  enabled: true
  encoding: UTF-8
  paths:
    - /path/to/foo.log
  fields_under_root: true
  fields:
    theme: foo
    maker: foo
  multiline.pattern: ^\d{4}-\d{2}-\d{2}
  multiline.negate: true
  multiline.match: after


# =====================================================================================================================
# 模型加载部分
# =====================================================================================================================
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false


# =====================================================================================================================
# 日志输出部分
# =====================================================================================================================
output.kafka:
  hosts: [
    "kafka-0.season.com:9092",
    "kafka-1.season.com:9092",
    "kafka-2.season.com:9092"
  ]
  topic: "season-os-log"
