#######################################################################################################################
#                                _      _      _                                   _                                  #
#                               | | o  | |    | |                                 | |                                 #
#                               | |    | |  _ | |   _   __, _|_         _  _  _   | |                                 #
#                               |/  |  |/  |/ |/ \_|/  /  |  |   |   | / |/ |/ |  |/                                  #
#                               |__/|_/|__/|__/\_/ |__/\_/|_/|_/o \_/|/  |  |  |_/|__/                                #
#                               |\                                  /|                                                #
#                               |/                                  \|                                                #
#######################################################################################################################
#
# 文件位置: /etc/filebeat/filebeat.yml
#


# =====================================================================================================================
# 日志采集部分
# =====================================================================================================================
filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/elasticsearch/elasticsearch.log
  fields:
    theme: elasticsearch
    ipaddr: demo.season.com
  fields_under_root: true
  multiline.pattern: ^\d{4}-\d{2}-\d{2}
  multiline.negate: true
  multiline.match: after
- type: log
  enabled: true
  paths:
    - /var/log/logstash/logstash.log
  fields:
    theme: logstash
    ipaddr: demo.season.com
  fields_under_root: true
  multiline.pattern: ^\d{4}-\d{2}-\d{2}
  multiline.negate: true
  multiline.match: after


# =====================================================================================================================
# 模型加载部分
# =====================================================================================================================
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false


# =====================================================================================================================
# 部分
# =====================================================================================================================
setup.template.settings:
  index.number_of_shards: 4


# =====================================================================================================================
# 日志输出部分
# =====================================================================================================================
output.kafka:
  hosts: [
      "elastic-0.season.com",
      "elastic-1.season.com",
      "elastic-2.season.com"
  ]
  topic: "middleware-log"
