# 使用 SSL 建立通信连接
# security.protocol=SSL
# 使用 SSL 建立通信连接, 附带 SASL 用户认证
# security.protocol=SASL_SSL
# 未用 SSL 建立通信连接, 附带 SASL 用户认证
# security.protocol=SASL_PLAINTEXT

# 验证服务端的 SSL 证书 (双向验证)
# ssl.keystore.location=/etc/kafka/kafka.keystore.p12
# ssl.keystore.password=season_4U
# ssl.keystore.type=PKCS12
# ssl.truststore.location=/etc/kafka/kafka.truststore.jks
# ssl.truststore.password=season_4U
# ssl.truststore.type=JKS

# sasl.mechanism=PLAIN (配套 SASL_SSL/ SASL_PLAINTEXT 使用)

