Client {
    // Kafka 软件注册服务时使用 Client 配置块
    org.apache.kafka.common.security.plain.PlainLoginModule required
    username="kafka"
    password="kafka_4U";
};
KafkaServer {
    // Kafka 软件启动服务时使用 KafkaServer 配置块
    org.apache.kafka.common.security.plain.PlainLoginModule required
    user_admin="admin_4U"
    username="admin"
    password="admin_4U"
    user_provider="provider_4U"
    user_consumer="consumer_4U";
};
KafkaClient {
    // Kafka 软件下属 kafka-topics.sh kafka-console-provider.sh kafka-console-consumer.sh 工具使用 KafkaClient 配置块
    org.apache.kafka.common.security.plain.PlainLoginModule required
    username="admin"
    password="admin_4U";
};

