#!/bin/bash
# -*- coding: utf-8 -*-
# common configure file


# =====================================================================================================================
# 网络配置
# =====================================================================================================================
bind 0.0.0.0
timeout 600
tcp-backlog 1024
# tls-ca-cert-file /etc/cert.d/file.crt
# tls-cert-file /etc/cert.d/file.pem
# tls-key-file /etc/cert.d/file.key


# =====================================================================================================================
# 内存配置
# =====================================================================================================================
maxmemory 0
maxmemory-policy allkeys-lru
# 设置软件的连接并发上限为 65503 个客户端连接, 预留 32 个文件句柄给 CONFIG_FDSET_INCR 使用
maxclients 65503


# =====================================================================================================================
# 持久化配置
# =====================================================================================================================
save 86400 1
save 7200  100
save 60    10000

stop-writes-on-bgsave-error yes
rdbcompression yes
rdbchecksum yes

appendonly yes
appendfsync everysec
no-appendfsync-on-rewrite yes
auto-aof-rewrite-percentage 100
auto-aof-rewrite-min-size 256mb
aof-load-truncated yes
aof-use-rdb-preamble yes


# =====================================================================================================================
# 性能配置
# =====================================================================================================================
repl-disable-tcp-nodelay no
repl-timeout 300
repl-backlog-size 6mb
slowlog-log-slower-than 10000
slowlog-max-len 2048


# =====================================================================================================================
# 服务结构配置
# =====================================================================================================================
daemonize no
loglevel notice
databases 16
io-threads 3
io-threads-do-reads no
supervised systemd

