#!/bin/bash
# -*- coding: utf-8 -*-


# =====================================================================================================================
# 网络配置
# =====================================================================================================================
bind 0.0.0.0
port 6379
timeout 600
tcp-backlog 1024
requirepass season_4U


# =====================================================================================================================
# 内存配置
# =====================================================================================================================
maxmemory 0
maxmemory-policy allkeys-lru
maxclients 65535


# =====================================================================================================================
# 持久化配置
# =====================================================================================================================
save 86400 1
save 7200  100
save 60    10000

dbfilename dump.rdb
stop-writes-on-bgsave-error yes
rdbcompression yes
rdbchecksum yes

appendonly yes
appendfilename appendonly.aof
appendfsync everysec
no-appendfsync-on-rewrite yes
auto-aof-rewrite-percentage 100
auto-aof-rewrite-min-size 256mb
aof-load-truncated yes
aof-use-rdb-preamble yes


# =====================================================================================================================
# 服务结构配置
# =====================================================================================================================
daemonize no
pidfile /var/redis/run/redis.pid
dir /var/redis/data
logfile /var/log/redis/redis.log
loglevel notice
databases 16
supervised systemd

