#!/bin/bash
# -*- coding: utf-8 -*-
# ...



# =====================================================================================================================
# 监听/ 连接配置
# =====================================================================================================================
# 监听配置项
bind 0.0.0.0
port 6379

# 连接配置项
maxclients 65535
timeout 600
requirepass season_4U


# =====================================================================================================================
# 进程/ 服务配置
# =====================================================================================================================
# 进程配置项
daemonize no
pidfile /var/redis/run/redis.pid

# 服务配置项
maxmemory 0
databases 16


# =====================================================================================================================
# 日志/ 数据配置
# =====================================================================================================================
# 日志配置项
loglevel notice
logfile /var/log/redis/redis.log

# 数据配置项
dir /var/redis/data

dbfilename dump.rdb
rdbcompression yes
save 86400 1

appendonly yes
appendfilename appendonly.aof
appendfsync everysec

