#!/bin/bash
# -*- coding: utf-8 -*-
#
# chkconfig: 35 99 99
#
#######################################################################################################################
#                                                                                                                     #
#                                                         o                                                           #
#                                             _  _    __,     _  _                                                    #
#                                            / |/ |  /  | |  / |/ |  /\/                                              #
#                                              |  |_/\_/|/|_/  |  |_/ /\_/                                            #
#                                                      /|                                                             #
#                                                      \|                                                             #
#######################################################################################################################
#
# Location: /etc/init.d/nginx
# Usage:
#    $ chkconfig nginx on
#    $ service nginx { start | stop | restart }


source /etc/init.d/functions


# =====================================================================================================================
# Check prerequisite
# =====================================================================================================================
if [[ ${#} != 1 ]]; then
    action "check parameter" /bin/false
    exit 1
else
    source ~/.bash_profile
    cd $(dirname ${0})
fi

EXEC=/usr/sbin/nginx
PROG=${EXEC##*/}

if [[ ! -f ${EXEC} ]] || [[ ! -x ${EXEC} ]]; then
    action "check ${EXEC}" /bin/false
    exit 1
fi


# =====================================================================================================================
# Script main part
# =====================================================================================================================
case ${1} in
    start )
        ${EXEC}
        ;;
    stop )
        ${EXEC} -s stop
        ;;
    status )
        status ${PROG}
        ;;
    restart )
        ${EXEC} -s stop
        ${EXEC}
        ;;
    reload )
        ${EXEC} -s reload
        ;;
    * )
        echo $"Usage: $0 { start | stop | status | restart | reload }"
        exit 2
        ;;
esac

exit 0
