#!/bin/bash
# -*- coding: utf-8 -*-
# /path/to/rabbitmq.conf


# =====================================================================================================================
# 网络配置
# =====================================================================================================================
# 明文端口配置
listeners.tcp = 5672
num_acceptors.tcp = 10
handshake_timeout = 10000

# SSL 端口和证书配置
# listeners.ssl = 5672
# num_acceptors.ssl = 10
# ssl_options.cacertifile = /etc/ca/file.cer
# ssl_options.certfile = /etc/ca/file.pem
# ssl_options.keyfile = /etc/ca/file.key
# ssl_options.verify = verify_none
# ssl_handshake_timeout = 10000

# 分布式端口配置
distribution.listener.interface = 0.0.0.0
distribution.listener.port_range.min = 25672
distribution.listener.port_range.max = 25672


# =====================================================================================================================
# 性能配置
# =====================================================================================================================
vm_memory_high_watermark.relative = 0.7
vm_memory_high_watermark_paging_ratio = 0.5
disk_free_limit.absolute = 4GB


# =====================================================================================================================
# 服务端配置
# =====================================================================================================================
max_message_size = 134217728
heartbeat = 60
default_vhost = season


# =====================================================================================================================
# 客户端配置
# =====================================================================================================================
channel_max = 128
channel_operation_timeout = 10000

