#!/bin/bash
# -*- coding: utf-8 -*-
# /path/to/rabbitmq.conf


# =====================================================================================================================
# 网络配置
# =====================================================================================================================
# 设置实例的业务监听端口
listeners.tcp.default = 5672
# 并发 10 个引导进程, 用于引导 AMQP 请求建立网络连接
num_acceptors.tcp = 10
# AMQP 请求的超时时间为 10000 毫秒 (10 秒钟)
handshake_timeout = 10000

# 设置实例的 SSL 监听端口
# listeners.ssl.default = 5671
# 并发 10 个引导进程, 用于引导 AMQPS 请求建立网络连接
# num_acceptors.ssl = 10
# CA 机构颁发的 SSL 权威证书文件
# ssl_options.cacertifile = /etc/ca/file.cer
# CA 机构颁发的 SSL 公钥证书文件
# ssl_options.certfile = /etc/ca/file.pem
# CA 机构颁发的 SSL 私钥证书文件
# ssl_options.keyfile = /etc/ca/file.key
# 单向 SSL 验证
# ssl_options.verify = verify_none
# AMQPS 请求的超时时间为 10000 毫秒 (10 秒钟)
# ssl_handshake_timeout = 10000

# 使用 0.0.0.0 地址绑定分布式通信端口
distribution.listener.interface = 0.0.0.0
# 设置 25672 端口作为分布式通信端口的阈值下限
distribution.listener.port_range.min = 25672
# 设置 25672 端口作为分布式通信端口的阈值上限
distribution.listener.port_range.max = 25672


# =====================================================================================================================
# 性能配置
# =====================================================================================================================
# 软件准用内存占主机内存资源的 70%
vm_memory_high_watermark.relative = 0.7
# 软件准用内存若消耗 50%, 软件把内存数据换页至磁盘, 软件性能下降
vm_memory_high_watermark_paging_ratio = 0.5
# 软件为数据目录所属的磁盘和文件系统保留 4GB 尺寸的空闲存储
disk_free_limit.absolute = 4GB


# =====================================================================================================================
# 服务端配置
# =====================================================================================================================
# 服务端接受的单条业务数据的尺寸阈值上限为 128MB
max_message_size = 134217728
# 服务端每隔 30 秒钟向客户端发送一个 AMQP 心跳请求, 如果连续 2 个心跳请求无响应, 判断客户端失联
heartbeat = 60
# 服务端允许建立不限数量的 TCP 连接
connection_max = infinity
# 服务端创建 season 虚拟机作为默认虚拟机
default_vhost = season
# 服务端创建 root 用户作为默认用户
default_user = root
# 服务端使用 season_4U 作为默认用户的认证密码
default_pass = season_4U
# 默认账号可使用任意地址访问
loopback_users.root = false


# =====================================================================================================================
# 客户端配置
# =====================================================================================================================
# 单个客户端连接最多能够打开 128 个数据通道
channel_max = 128

